# Generated by Django 5.1.5 on 2025-02-04 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='原价')),
                ('condition', models.CharField(choices=[('new', '全新'), ('like_new', '九成新'), ('good', '良好'), ('acceptable', '可接受')], max_length=20, verbose_name='成色')),
                ('description', models.TextField(verbose_name='描述')),
                ('image', models.ImageField(upload_to='books/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_sold', models.BooleanField(default=False, verbose_name='是否已售')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '二手书',
                'verbose_name_plural': '二手书',
                'ordering': ['-created_at'],
            },
        ),
    ]
